// Reflexion: distil a batch of recent raw memories into one or more
// long-term lessons. The package only handles the bucketing & content
// shape; the actual narrative is generated by an injected Distiller, which
// is usually backed by an LLM (and is trivial to fake in tests).
//
// # Why reflexion is its own concept
//
// Daily memories accumulate quickly and become noise. The legacy memories
// table reserved `long_term` and `dreams` layers but never wrote anything
// to them, so PMAgent could not benefit from "what we learned in May about
// chasing earnings beats". Reflexion is the periodic job that promotes
// daily noise into long-term signal: it groups memories by topic, asks the
// distiller for a one-paragraph lesson per group, and emits new Items that
// the persistence layer should store with kind="reflection",
// layer="long_term", and parent_id pointing back at the source.
package memory

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"
)

// minReflectionContentRunes is the lower bound on a distilled lesson's
// character count (Unicode runes, so a Chinese reflection of ~10 chars
// still passes). Anything shorter is almost certainly the LLM giving
// up — empty, "n/a", or a single fragment that lost its tail to the
// firstSentence truncation downstream. The threshold is intentionally
// permissive in the Chinese direction because a meaningful 中文 lesson
// can be ~20 runes ("减少在收盘前 30 分钟的被动追价") while a 30-rune
// English platitude ("To improve over time") is still useless.
const minReflectionContentRunes = 25

// reflectionPlatitudePattern matches the leading words of the generic
// motivational sentences we've observed the distiller emit when its
// input is itself templated (the OCS Selection 2026-05-25 batch all
// reduced to "To maximize the utility of research" — see commit notes).
// The regex is anchored at the start so a substring inside an
// otherwise-substantive lesson doesn't cause a false reject.
var reflectionPlatitudePattern = regexp.MustCompile(
	`(?i)^\s*(to\s+maximize\b|to\s+improve\b|to\s+ensure\b|ensure\s+that\b|always\s+focus\b|always\s+remember\b|it\s+is\s+important\b|the\s+key\s+is\b|in\s+order\s+to\b|为了\s*(让|实现|最大|提升|提高|确保)|要确保|要保证|要持续|应当持续|应当确保)`,
)

// reflectionTruncatedPatterns catches the failure mode where the LLM
// started emitting a markdown header / list / subordinate clause but got
// cut off before producing the actual lesson body. Observed in
// production: the OCS Selection 2026-05-26 batch wrote
//
//	"Lessons:* Researchers must"
//	"When encountering zero daily returns or missing data"
//
// as long_term reflections — both passed the 25-rune floor and the
// platitude blacklist but neither is a usable lesson. They were silently
// fanned out as "proposed skills" to every agent on the team and would
// have polluted the prompt resolver until a human noticed.
//
// Each pattern is anchored at start (`^`) and end (`$`) so it only
// fires on the whole content; a fully-formed lesson that happens to
// contain the word "Lessons:" inside it is not a false positive.
var reflectionTruncatedPatterns = []*regexp.Regexp{
	// "Lessons:* Researchers must", "Insights: To improve",
	// "Adjustments: Reduce" — markdown list header glued to a
	// half-sentence with no terminating punctuation.
	regexp.MustCompile(`(?i)^\s*(lessons?|insights?|adjustments?|hits?|misses?|recommendations?|key\s+takeaways?|takeaways?|action\s+items?|todo|notes?)\s*:\s*\*?\s*[^.!?。！？\n]{0,80}$`),
	// "When encountering zero daily returns or missing data" — leading
	// subordinate clause word with no main clause and no terminating
	// punctuation. We require at least 10 chars in the clause body so a
	// fully-formed "When X happens, do Y." (which has a period) still
	// passes.
	regexp.MustCompile(`(?i)^\s*(when|if|while|whenever|once|after|before|since|because|although|though|unless)\s+[^.!?。！？\n]{8,}[^.!?。！？\s]\s*$`),
	// Bare markdown header alone with no body: "Lessons:",
	// "Adjustments:" (these would also be caught by len<25 in most
	// cases, but list them explicitly for clarity).
	regexp.MustCompile(`(?i)^\s*(lessons?|insights?|adjustments?|hits?|misses?|recommendations?|key\s+takeaways?|takeaways?|action\s+items?|notes?)\s*:\s*$`),
}

// reflectionTerminalPunctuation lists the sentence terminators we
// consider valid endings for a polished reflection (ASCII + CJK + the
// closing quotation marks that legitimately follow them).
const reflectionTerminalPunctuation = ".!?。！？\"”』）)"

// endsWithSentenceTerminator reports whether `s` (already trimmed)
// ends with a recognised sentence terminator. A "lesson" without
// terminating punctuation is almost always a `finish_reason=length`
// truncation artefact.
func endsWithSentenceTerminator(s string) bool {
	if s == "" {
		return false
	}
	r := []rune(s)
	last := r[len(r)-1]
	for _, term := range reflectionTerminalPunctuation {
		if last == term {
			return true
		}
	}
	return false
}

// isLowQualityReflection reports whether a distilled lesson is too
// short, too generic, or visibly truncated to be worth persisting.
// Called in Reflect's per-group loop right after empty-trim, so an
// unhelpful LLM response never gets stored as a "long_term" memory and
// never gets broadcast to every agent as a "needs approval" proposed
// skill.
//
// Four-stage filter (cheapest checks first):
//  1. Length floor — catches the "got truncated to nothing" case where
//     downstream firstSentence(160) cut at the first period and left a
//     stub.
//  2. Anchored regex on known-bad opening phrases (English + Chinese)
//     — catches the "padded platitude" case where the model produced
//     enough characters to clear the length gate but said nothing.
//  3. Sentence terminator check — a polished lesson always ends in
//     `.` / `!` / `?` / `。` / `！` / `？`. Missing terminators are
//     overwhelmingly `finish_reason=length` cut-offs (the OCS Selection
//     2026-05-26 batch wrote "When encountering zero daily returns or
//     missing data" — 52 runes, no platitude, no terminator).
//  4. Anchored truncation patterns — list-header stubs and bare
//     subordinate clauses that the model never completed; see
//     reflectionTruncatedPatterns for the catalogue.
func isLowQualityReflection(content string) bool {
	trimmed := strings.TrimSpace(content)
	if trimmed == "" {
		return true
	}
	if len([]rune(trimmed)) < minReflectionContentRunes {
		return true
	}
	if reflectionPlatitudePattern.MatchString(trimmed) {
		return true
	}
	if !endsWithSentenceTerminator(trimmed) {
		return true
	}
	for _, pat := range reflectionTruncatedPatterns {
		if pat.MatchString(trimmed) {
			return true
		}
	}
	return false
}

// Distiller generates a narrative lesson from a group of related memories.
// Implementations are usually thin wrappers around an LLM completion;
// tests can use a deterministic fake.
type Distiller interface {
	Distill(ctx context.Context, theme string, items []Item) (string, error)
}

// DistillerFunc adapts an ordinary function to the Distiller interface.
type DistillerFunc func(ctx context.Context, theme string, items []Item) (string, error)

// Distill calls f.
func (f DistillerFunc) Distill(ctx context.Context, theme string, items []Item) (string, error) {
	return f(ctx, theme, items)
}

// ReflectParams configures one reflexion run.
type ReflectParams struct {
	// FundID is propagated onto every emitted reflection.
	FundID string
	// Now is the wall-clock time stamped onto reflections; zero means
	// time.Now.
	Now time.Time
	// MinGroupSize is the minimum number of memories required to emit a
	// reflection for a group. Smaller groups are dropped (their content
	// stays in the raw layer). Default: 3.
	MinGroupSize int
	// MaxGroups caps the number of reflection items emitted in one run, to
	// keep LLM cost predictable. 0 means unlimited.
	MaxGroups int
	// MinAvgImportance is the minimum average importance a group must have
	// for a reflection to be emitted. Default: 0 (no filter).
	MinAvgImportance float64
	// MaxItemsPerGroup caps how many raw memories are sent to the distiller.
	// 0 means unlimited.
	MaxItemsPerGroup int
	// MaxItemContentRunes caps each source memory content before distillation.
	// 0 means unlimited.
	MaxItemContentRunes int
}

// ErrNothingToReflect is returned by Reflect when no group passes the
// filters; callers can swallow it.
var ErrNothingToReflect = errors.New("memory: nothing to reflect on")

// Reflect groups items by tag-derived theme, runs the distiller for each
// group, and returns a list of new Items to persist as reflections. The
// new Items have:
//
//   - Layer = "long_term"
//   - Kind  = "reflection"
//   - ParentID = "" (callers fan-out and write parent links per source)
//   - Tags    = group theme + every distinct tag in the group
//   - Importance = average importance of the group, clipped to [0, 1]
//
// The Distiller is called once per group; if it returns an error the
// reflection for that group is skipped (the rest still proceed).
func Reflect(ctx context.Context, items []Item, distiller Distiller, p ReflectParams) ([]Item, error) {
	if distiller == nil {
		return nil, errors.New("memory: Distiller is required")
	}
	min := p.MinGroupSize
	if min <= 0 {
		min = 3
	}
	now := p.Now
	if now.IsZero() {
		now = time.Now()
	}

	groups := groupByTheme(items)
	themes := make([]string, 0, len(groups))
	for t := range groups {
		themes = append(themes, t)
	}
	sort.Strings(themes)

	var out []Item
	for _, theme := range themes {
		g := groups[theme]
		if len(g) < min {
			continue
		}
		avg := averageImportance(g)
		if avg < p.MinAvgImportance {
			continue
		}
		distillItems := limitDistillerItems(g, p.MaxItemsPerGroup, p.MaxItemContentRunes)
		content, err := distiller.Distill(ctx, theme, distillItems)
		if err != nil {
			// Continue with the other groups; a flaky LLM should not
			// kill the whole run.
			continue
		}
		content = strings.TrimSpace(content)
		if content == "" {
			continue
		}
		// Drop low-quality LLM output so it never pollutes the
		// long_term layer (which the agent skill proposer reads
		// from) — see isLowQualityReflection rationale.
		if isLowQualityReflection(content) {
			continue
		}

		out = append(out, Item{
			FundID:     p.FundID,
			Layer:      "long_term",
			Kind:       "reflection",
			Title:      fmt.Sprintf("reflection: %s", theme),
			Content:    content,
			Tags:       collectTags(g, theme),
			Importance: clamp01(avg),
			CreatedAt:  now,
		})
		if p.MaxGroups > 0 && len(out) >= p.MaxGroups {
			break
		}
	}
	if len(out) == 0 {
		return nil, ErrNothingToReflect
	}
	return out, nil
}

func limitDistillerItems(items []Item, maxItems, maxContentRunes int) []Item {
	if maxItems <= 0 && maxContentRunes <= 0 {
		return items
	}
	n := len(items)
	if maxItems > 0 && n > maxItems {
		n = maxItems
	}
	out := make([]Item, 0, n)
	for i := 0; i < n; i++ {
		cp := items[i]
		if maxContentRunes > 0 {
			cp.Content = truncateMemoryRunes(cp.Content, maxContentRunes)
		}
		out = append(out, cp)
	}
	return out
}

func truncateMemoryRunes(s string, max int) string {
	trimmed := strings.TrimSpace(s)
	if max <= 0 || trimmed == "" {
		return trimmed
	}
	runes := []rune(trimmed)
	if len(runes) <= max {
		return trimmed
	}
	return string(runes[:max]) + "\n...[truncated]"
}

// groupByTheme buckets items by their first non-trivial tag; if no tag is
// present, the item is grouped under "general".
func groupByTheme(items []Item) map[string][]Item {
	groups := map[string][]Item{}
	for _, it := range items {
		theme := pickTheme(it.Tags)
		groups[theme] = append(groups[theme], it)
	}
	return groups
}

// trivialTags are tags that are too generic to drive grouping.
var trivialTags = map[string]struct{}{
	"":                {},
	"market-research": {},
	"self_learning":   {},
}

func pickTheme(tags []string) string {
	for _, t := range tags {
		lc := strings.ToLower(strings.TrimSpace(t))
		if _, skip := trivialTags[lc]; skip {
			continue
		}
		return lc
	}
	return "general"
}

func averageImportance(items []Item) float64 {
	if len(items) == 0 {
		return 0
	}
	sum := 0.0
	for _, it := range items {
		sum += it.Importance
	}
	return sum / float64(len(items))
}

func collectTags(items []Item, theme string) []string {
	seen := map[string]struct{}{theme: {}}
	out := []string{theme}
	for _, it := range items {
		for _, t := range it.Tags {
			lc := strings.ToLower(strings.TrimSpace(t))
			if _, ok := seen[lc]; ok || lc == "" {
				continue
			}
			seen[lc] = struct{}{}
			out = append(out, lc)
		}
	}
	sort.Strings(out)
	return out
}
