// Reflexion: distil a batch of recent raw memories into one or more
// long-term lessons. The package only handles the bucketing & content
// shape; the actual narrative is generated by an injected Distiller, which
// is usually backed by an LLM (and is trivial to fake in tests).
//
// # Why reflexion is its own concept
//
// Daily memories accumulate quickly and become noise. The legacy memories
// table reserved `long_term` and `dreams` layers but never wrote anything
// to them, so PMAgent could not benefit from "what we learned in May about
// chasing earnings beats". Reflexion is the periodic job that promotes
// daily noise into long-term signal: it groups memories by topic, asks the
// distiller for a one-paragraph lesson per group, and emits new Items that
// the persistence layer should store with kind="reflection",
// layer="long_term", and parent_id pointing back at the source.
package memory

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"
)

// Distiller generates a narrative lesson from a group of related memories.
// Implementations are usually thin wrappers around an LLM completion;
// tests can use a deterministic fake.
type Distiller interface {
	Distill(ctx context.Context, theme string, items []Item) (string, error)
}

// DistillerFunc adapts an ordinary function to the Distiller interface.
type DistillerFunc func(ctx context.Context, theme string, items []Item) (string, error)

// Distill calls f.
func (f DistillerFunc) Distill(ctx context.Context, theme string, items []Item) (string, error) {
	return f(ctx, theme, items)
}

// ReflectParams configures one reflexion run.
type ReflectParams struct {
	// FundID is propagated onto every emitted reflection.
	FundID string
	// Now is the wall-clock time stamped onto reflections; zero means
	// time.Now.
	Now time.Time
	// MinGroupSize is the minimum number of memories required to emit a
	// reflection for a group. Smaller groups are dropped (their content
	// stays in the raw layer). Default: 3.
	MinGroupSize int
	// MaxGroups caps the number of reflection items emitted in one run, to
	// keep LLM cost predictable. 0 means unlimited.
	MaxGroups int
	// MinAvgImportance is the minimum average importance a group must have
	// for a reflection to be emitted. Default: 0 (no filter).
	MinAvgImportance float64
	// MaxItemsPerGroup caps how many raw memories are sent to the distiller.
	// 0 means unlimited.
	MaxItemsPerGroup int
	// MaxItemContentRunes caps each source memory content before distillation.
	// 0 means unlimited.
	MaxItemContentRunes int
}

// ErrNothingToReflect is returned by Reflect when no group passes the
// filters; callers can swallow it.
var ErrNothingToReflect = errors.New("memory: nothing to reflect on")

// Reflect groups items by tag-derived theme, runs the distiller for each
// group, and returns a list of new Items to persist as reflections. The
// new Items have:
//
//   - Layer = "long_term"
//   - Kind  = "reflection"
//   - ParentID = "" (callers fan-out and write parent links per source)
//   - Tags    = group theme + every distinct tag in the group
//   - Importance = average importance of the group, clipped to [0, 1]
//
// The Distiller is called once per group; if it returns an error the
// reflection for that group is skipped (the rest still proceed).
func Reflect(ctx context.Context, items []Item, distiller Distiller, p ReflectParams) ([]Item, error) {
	if distiller == nil {
		return nil, errors.New("memory: Distiller is required")
	}
	min := p.MinGroupSize
	if min <= 0 {
		min = 3
	}
	now := p.Now
	if now.IsZero() {
		now = time.Now()
	}

	groups := groupByTheme(items)
	themes := make([]string, 0, len(groups))
	for t := range groups {
		themes = append(themes, t)
	}
	sort.Strings(themes)

	var out []Item
	for _, theme := range themes {
		g := groups[theme]
		if len(g) < min {
			continue
		}
		avg := averageImportance(g)
		if avg < p.MinAvgImportance {
			continue
		}
		distillItems := limitDistillerItems(g, p.MaxItemsPerGroup, p.MaxItemContentRunes)
		content, err := distiller.Distill(ctx, theme, distillItems)
		if err != nil {
			// Continue with the other groups; a flaky LLM should not
			// kill the whole run.
			continue
		}
		content = strings.TrimSpace(content)
		if content == "" {
			continue
		}

		out = append(out, Item{
			FundID:     p.FundID,
			Layer:      "long_term",
			Kind:       "reflection",
			Title:      fmt.Sprintf("reflection: %s", theme),
			Content:    content,
			Tags:       collectTags(g, theme),
			Importance: clamp01(avg),
			CreatedAt:  now,
		})
		if p.MaxGroups > 0 && len(out) >= p.MaxGroups {
			break
		}
	}
	if len(out) == 0 {
		return nil, ErrNothingToReflect
	}
	return out, nil
}

func limitDistillerItems(items []Item, maxItems, maxContentRunes int) []Item {
	if maxItems <= 0 && maxContentRunes <= 0 {
		return items
	}
	n := len(items)
	if maxItems > 0 && n > maxItems {
		n = maxItems
	}
	out := make([]Item, 0, n)
	for i := 0; i < n; i++ {
		cp := items[i]
		if maxContentRunes > 0 {
			cp.Content = truncateMemoryRunes(cp.Content, maxContentRunes)
		}
		out = append(out, cp)
	}
	return out
}

func truncateMemoryRunes(s string, max int) string {
	trimmed := strings.TrimSpace(s)
	if max <= 0 || trimmed == "" {
		return trimmed
	}
	runes := []rune(trimmed)
	if len(runes) <= max {
		return trimmed
	}
	return string(runes[:max]) + "\n...[truncated]"
}

// groupByTheme buckets items by their first non-trivial tag; if no tag is
// present, the item is grouped under "general".
func groupByTheme(items []Item) map[string][]Item {
	groups := map[string][]Item{}
	for _, it := range items {
		theme := pickTheme(it.Tags)
		groups[theme] = append(groups[theme], it)
	}
	return groups
}

// trivialTags are tags that are too generic to drive grouping.
var trivialTags = map[string]struct{}{
	"":                {},
	"market-research": {},
	"self_learning":   {},
}

func pickTheme(tags []string) string {
	for _, t := range tags {
		lc := strings.ToLower(strings.TrimSpace(t))
		if _, skip := trivialTags[lc]; skip {
			continue
		}
		return lc
	}
	return "general"
}

func averageImportance(items []Item) float64 {
	if len(items) == 0 {
		return 0
	}
	sum := 0.0
	for _, it := range items {
		sum += it.Importance
	}
	return sum / float64(len(items))
}

func collectTags(items []Item, theme string) []string {
	seen := map[string]struct{}{theme: {}}
	out := []string{theme}
	for _, it := range items {
		for _, t := range it.Tags {
			lc := strings.ToLower(strings.TrimSpace(t))
			if _, ok := seen[lc]; ok || lc == "" {
				continue
			}
			seen[lc] = struct{}{}
			out = append(out, lc)
		}
	}
	sort.Strings(out)
	return out
}
